language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

git:
  depth: 10
  submodules: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - composer install --prefer-dist --no-interaction
  - pecl install ast-1.0.1

script:
  - vendor/bin/phpcs -n
  - vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always
  - composer require phan/phan -n
  - vendor/bin/phan
  - bash <(curl -s https://codecov.io/bash)
